[package]
name = "web_scrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
printpdf = "0.7.0"
reqwest = { version = "0.12.5", features = ["json"] }
scraper = "0.19.0"
tokio = { version = "1.38.0", features = ["full"] }
